# Generated by Django 4.1.5 on 2023-01-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='las_update',
            new_name='last_update',
        ),
    ]
