# Generated by Django 4.1.5 on 2023-01-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_las_update_product_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cat',
            new_name='cart',
        ),
    ]
